// AUTO-GENERATED by scripts/transform-spring-2026.py — do not edit.
// Source: SE Tourney + LeagueOps May 2 jamboree CSV. Scores intentionally stripped
// per NFYLL rec-league policy (no public competitive results).

import type { Season, Program, Game } from '../../../lib/leagueops';

export const season: Season = {
  "slug": "spring-2026",
  "name": "NFYLL Spring 2026",
  "startDate": "2026-02-28",
  "endDate": "2026-05-02",
  "status": "completed"
};

export const programs: Program[] = [
  {
    "id": "creeks",
    "name": "Creeks Youth Lacrosse",
    "shortName": "Creeks",
    "logoUrl": "/clubs/creeks.png"
  },
  {
    "id": "ponte-vedra",
    "name": "Ponte Vedra Riptide Lacrosse",
    "shortName": "Riptide",
    "logoUrl": "/clubs/ponte-vedra.png"
  },
  {
    "id": "jax-lax",
    "name": "Jax Lax",
    "shortName": "Jax Lax",
    "logoUrl": "/clubs/jax-lax.png"
  },
  {
    "id": "filc",
    "name": "Fleming Island Lacrosse Club",
    "shortName": "Fleming Island",
    "logoUrl": "/clubs/filc.png"
  },
  {
    "id": "amelia-island",
    "name": "Amelia Island Hammerheads",
    "shortName": "Hammerheads",
    "logoUrl": "/clubs/amelia-island.png"
  },
  {
    "id": "bold-city",
    "name": "Bold City Eagles",
    "shortName": "Bold City"
  },
  {
    "id": "redhawks",
    "name": "Redhawks",
    "shortName": "Redhawks"
  },
  {
    "id": "bulldogs-lc",
    "name": "Bulldogs LC",
    "shortName": "Bulldogs"
  }
];

// 190 games
export const games: Game[] = [
  {
    "id": "se-12-Grade-4v4-P1-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "Creeks Blue 8u",
    "awayTeamId": "8U Riptide White",
    "startsAt": "2026-02-28T09:00:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P2-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "Fleming Island 1/2",
    "awayTeamId": "8U Riptide Black",
    "startsAt": "2026-02-28T09:45:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P3-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "Jax Lax - 8U",
    "awayTeamId": "8U Riptide Gray",
    "startsAt": "2026-02-28T10:30:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P4-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Blue",
    "awayTeamId": "Creeks Green 8u",
    "startsAt": "2026-02-28T11:15:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P5-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide White",
    "awayTeamId": "Fleming Island 1/2",
    "startsAt": "2026-03-07T09:00:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P6-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Gray",
    "awayTeamId": "Creeks Green 8u",
    "startsAt": "2026-03-07T09:45:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P7-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Black",
    "awayTeamId": "Creeks Blue 8u",
    "startsAt": "2026-03-07T10:30:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P8-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Blue",
    "awayTeamId": "Jax Lax - 8U",
    "startsAt": "2026-03-07T11:15:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P9-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide White",
    "awayTeamId": "8U Riptide Black",
    "startsAt": "2026-03-14T09:00:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P10-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Blue",
    "awayTeamId": "8U Riptide Gray",
    "startsAt": "2026-03-14T09:45:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P11-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "Fleming Island 1/2",
    "awayTeamId": "Creeks Green 8u",
    "startsAt": "2026-03-14T10:30:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P12-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "Jax Lax - 8U",
    "awayTeamId": "Creeks Blue 8u",
    "startsAt": "2026-03-14T11:15:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P13-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide White",
    "awayTeamId": "Jax Lax - 8U",
    "startsAt": "2026-03-28T09:00:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P14-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Gray",
    "awayTeamId": "Fleming Island 1/2",
    "startsAt": "2026-03-28T09:45:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P15-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Black",
    "awayTeamId": "Creeks Green 8u",
    "startsAt": "2026-03-28T10:30:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P16-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Blue",
    "awayTeamId": "Creeks Blue 8u",
    "startsAt": "2026-03-28T11:15:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P17-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide White",
    "awayTeamId": "Creeks Blue 8u",
    "startsAt": "2026-04-11T09:00:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P18-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "Creeks Green 8u",
    "awayTeamId": "8U Riptide Gray",
    "startsAt": "2026-04-11T09:45:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P19-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Blue",
    "awayTeamId": "Fleming Island 1/2",
    "startsAt": "2026-04-11T10:30:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P20-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Black",
    "awayTeamId": "Jax Lax - 8U",
    "startsAt": "2026-04-11T11:15:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P21-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Blue",
    "awayTeamId": "Jax Lax - 8U",
    "startsAt": "2026-04-18T09:00:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P22-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Black",
    "awayTeamId": "Fleming Island 1/2",
    "startsAt": "2026-04-18T09:45:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P23-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Gray",
    "awayTeamId": "Creeks Green 8u",
    "startsAt": "2026-04-18T10:30:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P24-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide White",
    "awayTeamId": "Creeks Blue 8u",
    "startsAt": "2026-04-18T11:15:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P24-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Gray",
    "awayTeamId": "Jax Lax - 8U",
    "startsAt": "2026-04-25T09:00:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P26-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide White",
    "awayTeamId": "Fleming Island 1/2",
    "startsAt": "2026-04-25T09:45:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P27-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Blue",
    "awayTeamId": "Creeks Green 8u",
    "startsAt": "2026-04-25T10:30:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-12-Grade-4v4-P28-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade 4v4",
    "homeTeamId": "8U Riptide Black",
    "awayTeamId": "Creeks Blue 8u",
    "startsAt": "2026-04-25T11:15:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P1-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Fleming Island 3/4",
    "awayTeamId": "10U Riptide Blue",
    "startsAt": "2026-02-28T09:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P2-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Jax Lax - 10U",
    "awayTeamId": "10U Riptide Black",
    "startsAt": "2026-02-28T10:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P3-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Gray",
    "awayTeamId": "Creeks Blue 10u",
    "startsAt": "2026-02-28T11:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P4-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Creeks Green 10u",
    "awayTeamId": "10U Riptide Navy",
    "startsAt": "2026-02-28T12:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P5-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide White",
    "awayTeamId": "Creeks Blue 10u",
    "startsAt": "2026-02-28T13:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P6-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Blue",
    "awayTeamId": "Creeks Blue 10u",
    "startsAt": "2026-03-07T09:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P7-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Creeks Green 10u",
    "awayTeamId": "10U Riptide Gray",
    "startsAt": "2026-03-07T10:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P8-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Jax Lax - 10U Titans",
    "awayTeamId": "10U Riptide Navy",
    "startsAt": "2026-03-07T11:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P10-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Jax Lax - 10U",
    "awayTeamId": "10U Riptide White",
    "startsAt": "2026-03-07T12:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P11-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Fleming Island 3/4",
    "awayTeamId": "10U Riptide Black",
    "startsAt": "2026-03-07T13:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P12-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Black",
    "awayTeamId": "10U Riptide Blue",
    "startsAt": "2026-03-14T09:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P13-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Gray",
    "awayTeamId": "10U Riptide Navy",
    "startsAt": "2026-03-14T10:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P14-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Jax Lax - 10U",
    "awayTeamId": "Creeks Green 10u",
    "startsAt": "2026-03-14T11:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P15-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Jax Lax - 10U Titans",
    "awayTeamId": "Fleming Island 3/4",
    "startsAt": "2026-03-14T12:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P16-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Creeks Blue 10u",
    "awayTeamId": "Jax Lax - 10U",
    "startsAt": "2026-03-14T13:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P17-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Fleming Island 3/4",
    "awayTeamId": "10U Riptide Gray",
    "startsAt": "2026-03-28T09:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P18-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Jax Lax - 10U",
    "awayTeamId": "10U Riptide Blue",
    "startsAt": "2026-03-28T10:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P19-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "10U Riptide White",
    "startsAt": "2026-03-28T11:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P20-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Jax Lax - 10U Titans",
    "awayTeamId": "10U Riptide Navy",
    "startsAt": "2026-03-28T12:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P21-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Creeks Blue 10u",
    "awayTeamId": "10U Riptide Black",
    "startsAt": "2026-03-28T13:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P22-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Creeks Green 10u",
    "startsAt": "2026-03-28T14:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P23-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Black",
    "awayTeamId": "10U Riptide Gray",
    "startsAt": "2026-04-11T09:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P24-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Blue",
    "awayTeamId": "Creeks Green 10u",
    "startsAt": "2026-04-11T10:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P25-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Navy",
    "awayTeamId": "Fleming Island 3/4",
    "startsAt": "2026-04-11T11:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P27-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Creeks Blue 10u",
    "awayTeamId": "Jax Lax - 10U",
    "startsAt": "2026-04-11T12:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P26-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide White",
    "awayTeamId": "Jax Lax - 10U Titans",
    "startsAt": "2026-04-11T13:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P28-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Fleming Island 3/4",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-04-11T14:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P29-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Black",
    "awayTeamId": "Jax Lax - 10U Titans",
    "startsAt": "2026-04-18T09:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P30-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Blue",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-04-18T10:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P31-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Navy",
    "awayTeamId": "Jax Lax - 10U",
    "startsAt": "2026-04-18T11:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P32-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Creeks Blue 10u",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-04-18T12:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P33-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Gray",
    "awayTeamId": "Creeks Green 10u",
    "startsAt": "2026-04-18T13:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P34-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide White",
    "awayTeamId": "Fleming Island 3/4",
    "startsAt": "2026-04-18T14:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P35-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Gray",
    "awayTeamId": "Jax Lax - 10U",
    "startsAt": "2026-04-25T09:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P36-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Navy",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-04-25T10:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P37-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Blue",
    "awayTeamId": "Jax Lax - 10U Titans",
    "startsAt": "2026-04-25T11:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P38-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide Black",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-04-25T12:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P39-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "10U Riptide White",
    "awayTeamId": "Creeks Green 10u",
    "startsAt": "2026-04-25T13:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-34-Grade-7V7-P40-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade 7V7",
    "homeTeamId": "Creeks Blue 10u",
    "awayTeamId": "Fleming Island 3/4",
    "startsAt": "2026-04-25T14:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P2-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Navy",
    "awayTeamId": "Fleming Island 5/6",
    "startsAt": "2026-02-28T09:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P1-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Black",
    "awayTeamId": "Bold City Eagles 12U",
    "startsAt": "2026-02-28T10:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P3-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Creeks Blue 12u",
    "awayTeamId": "RedHawks 12U",
    "startsAt": "2026-02-28T11:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P4-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Jax Lax - 12U",
    "awayTeamId": "12U Riptide White",
    "startsAt": "2026-02-28T12:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P5-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Creeks Green 12u",
    "awayTeamId": "12U Riptide Blue",
    "startsAt": "2026-02-28T13:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P6-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Gray",
    "awayTeamId": "RedHawks 12U",
    "startsAt": "2026-02-28T14:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P7-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Creeks Green 12u",
    "awayTeamId": "12U Riptide Black",
    "startsAt": "2026-03-07T09:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P8-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Fleming Island 5/6",
    "startsAt": "2026-03-07T10:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P9-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "RedHawks 12U",
    "awayTeamId": "Creeks Green 12u",
    "startsAt": "2026-03-07T11:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P10-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "12U Riptide White",
    "startsAt": "2026-03-07T12:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P11-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "RedHawks 12U",
    "awayTeamId": "12U Riptide Blue",
    "startsAt": "2026-03-07T13:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P12-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Jax Lax - 12U",
    "awayTeamId": "12U Riptide Navy",
    "startsAt": "2026-03-07T14:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P13-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Creeks Blue 12u",
    "awayTeamId": "12U Riptide Gray",
    "startsAt": "2026-03-07T15:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P14-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Black",
    "awayTeamId": "12U Riptide Blue",
    "startsAt": "2026-03-14T09:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P15-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Gray",
    "awayTeamId": "12U Riptide Navy",
    "startsAt": "2026-03-14T10:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P16-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Creeks Blue 12u",
    "awayTeamId": "Fleming Island 5/6",
    "startsAt": "2026-03-14T11:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P17-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Jax Lax - 12U",
    "awayTeamId": "Creeks Green 12u",
    "startsAt": "2026-03-14T12:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P18-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Fleming Island 5/6",
    "awayTeamId": "12U Riptide Gray",
    "startsAt": "2026-03-28T09:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P19-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "12U Riptide Navy",
    "startsAt": "2026-03-28T10:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P21-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Jax Lax - 12U",
    "awayTeamId": "12U Riptide White",
    "startsAt": "2026-03-28T12:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P22-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "12U Riptide Black",
    "startsAt": "2026-03-28T13:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P23-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Creeks Green 12u",
    "awayTeamId": "Bold City Eagles 12U",
    "startsAt": "2026-03-28T14:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P24-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Creeks Blue 12u",
    "awayTeamId": "12U Riptide Blue",
    "startsAt": "2026-03-28T15:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P25-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Black",
    "awayTeamId": "Jax Lax - 12U",
    "startsAt": "2026-04-11T09:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P26-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Blue",
    "awayTeamId": "Fleming Island 5/6",
    "startsAt": "2026-04-11T10:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P28-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Gray",
    "awayTeamId": "Creeks Green 12u",
    "startsAt": "2026-04-11T11:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P29-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Fleming Island 5/6",
    "startsAt": "2026-04-11T12:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P27-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Bold City Eagles 12U",
    "awayTeamId": "Creeks Blue 12u",
    "startsAt": "2026-04-11T13:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P30-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Navy",
    "awayTeamId": "12U Riptide White",
    "startsAt": "2026-04-11T14:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P31-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Bold City Eagles 12U",
    "startsAt": "2026-04-11T15:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P44-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Blue",
    "awayTeamId": "Jax Lax - 12U",
    "startsAt": "2026-04-18T09:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P32-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Gray",
    "awayTeamId": "Fleming Island 5/6",
    "startsAt": "2026-04-18T10:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P33-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "RedHawks 12U",
    "awayTeamId": "12U Riptide Black",
    "startsAt": "2026-04-18T11:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P34-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Bold City Eagles 12U",
    "awayTeamId": "Creeks Green 12u",
    "startsAt": "2026-04-18T12:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P35-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Fleming Island 5/6",
    "awayTeamId": "Creeks Blue 12u",
    "startsAt": "2026-04-18T13:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P36-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "RedHawks 12U",
    "awayTeamId": "12U Riptide Navy",
    "startsAt": "2026-04-18T14:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P37-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Bold City Eagles 12U",
    "awayTeamId": "12U Riptide White",
    "startsAt": "2026-04-18T15:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P38-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Black",
    "awayTeamId": "Fleming Island 5/6",
    "startsAt": "2026-04-25T09:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P39-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Creeks Blue 12u",
    "awayTeamId": "12U Riptide Navy",
    "startsAt": "2026-04-25T10:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P40-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Gray",
    "awayTeamId": "Bold City Eagles 12U",
    "startsAt": "2026-04-25T11:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P41-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Jax Lax - 12U",
    "startsAt": "2026-04-25T12:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P42-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "12U Riptide Blue",
    "awayTeamId": "12U Riptide White",
    "startsAt": "2026-04-25T13:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-56-Grade-10v10-P43-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade 10v10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Creeks Green 12u",
    "startsAt": "2026-04-25T14:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P1-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "14U Riptide Black",
    "awayTeamId": "Bold City Eagles 14U",
    "startsAt": "2026-02-28T09:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P2-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Bulldogs LC",
    "awayTeamId": "14U Riptide White",
    "startsAt": "2026-02-28T10:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P3-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "14U Riptide Blue",
    "awayTeamId": "Creeks Blue 14u",
    "startsAt": "2026-02-28T11:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P4-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "RedHawks 14U",
    "awayTeamId": "14U Riptide White",
    "startsAt": "2026-02-28T12:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P5-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Creeks Green 14u",
    "awayTeamId": "Fleming Island 7/8",
    "startsAt": "2026-02-28T13:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P6-2026-02-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Jax Lax - 14U",
    "awayTeamId": "RedHawks 14U",
    "startsAt": "2026-02-28T14:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P7-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Jax Lax - 14U",
    "awayTeamId": "Fleming Island 7/8",
    "startsAt": "2026-03-07T09:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P8-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "14U Riptide Black",
    "awayTeamId": "14U Riptide Blue",
    "startsAt": "2026-03-07T10:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P9-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Creeks Green 14u",
    "startsAt": "2026-03-07T11:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P10-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "RedHawks 14U",
    "awayTeamId": "Bulldogs LC",
    "startsAt": "2026-03-07T12:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P11-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Creeks Blue 14u",
    "awayTeamId": "14U Riptide White",
    "startsAt": "2026-03-07T13:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P12-2026-03-07",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "RedHawks 14U",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-03-07T14:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P13-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "14U Riptide Black",
    "awayTeamId": "14U Riptide Blue",
    "startsAt": "2026-03-14T09:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P14-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Creeks Blue 14u",
    "awayTeamId": "Jax Lax - 14U",
    "startsAt": "2026-03-14T10:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P15-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Creeks Green 14u",
    "awayTeamId": "Bulldogs LC",
    "startsAt": "2026-03-14T11:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P16-2026-03-14",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Fleming Island 7/8",
    "awayTeamId": "Creeks Blue 14u",
    "startsAt": "2026-03-14T12:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P17-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Jax Lax - 14U",
    "awayTeamId": "14U Riptide White",
    "startsAt": "2026-03-28T09:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P18-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Bold City Eagles 14U",
    "awayTeamId": "Creeks Blue 14u",
    "startsAt": "2026-03-28T10:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P19-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "RedHawks 14U",
    "awayTeamId": "Bulldogs LC",
    "startsAt": "2026-03-28T11:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P20-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "14U Riptide Black",
    "startsAt": "2026-03-28T12:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P21-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Bold City Eagles 14U",
    "awayTeamId": "Creeks Green 14u",
    "startsAt": "2026-03-28T13:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P22-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "RedHawks 14U",
    "awayTeamId": "Fleming Island 7/8",
    "startsAt": "2026-03-28T14:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P23-2026-03-28",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "14U Riptide Blue",
    "startsAt": "2026-03-28T15:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P24-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "14U Riptide White",
    "awayTeamId": "Creeks Green 14u",
    "startsAt": "2026-04-11T09:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P25-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "14U Riptide Blue",
    "awayTeamId": "Creeks Blue 14u",
    "startsAt": "2026-04-11T10:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P26-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Fleming Island 7/8",
    "startsAt": "2026-04-11T11:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P27-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Jax Lax - 14U",
    "awayTeamId": "14U Riptide Black",
    "startsAt": "2026-04-11T12:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P28-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Bulldogs LC",
    "startsAt": "2026-04-11T13:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P29-2026-04-11",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Bold City Eagles 14U",
    "awayTeamId": "Fleming Island 7/8",
    "startsAt": "2026-04-11T14:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P30-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "14U Riptide Blue",
    "awayTeamId": "Creeks Green 14u",
    "startsAt": "2026-04-18T09:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P36-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Bulldogs LC",
    "awayTeamId": "Creeks Blue 14u",
    "startsAt": "2026-04-18T10:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P31-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Bold City Eagles 14U",
    "awayTeamId": "RedHawks 14U",
    "startsAt": "2026-04-18T11:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P32-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "14U Riptide White",
    "startsAt": "2026-04-18T12:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P33-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Jax Lax - 14U",
    "awayTeamId": "Fleming Island 7/8",
    "startsAt": "2026-04-18T13:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P34-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "RedHawks 14U",
    "awayTeamId": "14U Riptide Black",
    "startsAt": "2026-04-18T14:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P35-2026-04-18",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Jax Lax - 14U",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-04-18T15:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P37-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "14U Riptide Blue",
    "awayTeamId": "Jax Lax - 14U",
    "startsAt": "2026-04-25T09:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P38-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Bold City Eagles 14U",
    "startsAt": "2026-04-25T10:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P39-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Fleming Island 7/8",
    "awayTeamId": "14U Riptide White",
    "startsAt": "2026-04-25T11:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P40-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Creeks Blue 14u",
    "startsAt": "2026-04-25T12:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "se-78-Grade-10V10-P41-2026-04-25",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade 10V10",
    "homeTeamId": "Creeks Green 14u",
    "awayTeamId": "14U Riptide Black",
    "startsAt": "2026-04-25T13:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-12U_Riptide_Navy-Bold_City_Eagles-09:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide Navy",
    "awayTeamId": "Bold City Eagles",
    "startsAt": "2026-05-02T09:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Blue-10U_Riptide_Blue-09:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Creeks Blue",
    "awayTeamId": "10U Riptide Blue",
    "startsAt": "2026-05-02T09:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Blue-8U_Riptide_White-09:00",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade",
    "homeTeamId": "Creeks Blue",
    "awayTeamId": "8U Riptide White",
    "startsAt": "2026-05-02T09:00:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Riptide_Black-Creeks_Blue-09:00",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade",
    "homeTeamId": "Riptide Black",
    "awayTeamId": "Creeks Blue",
    "startsAt": "2026-05-02T09:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Hammerhead-10U_Riptide_Black-09:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "10U Riptide Black",
    "startsAt": "2026-05-02T09:00:00-05:00",
    "venue": {
      "name": "Field 3",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Bold_City_Eagles-Riptide_Blue-09:00",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade",
    "homeTeamId": "Bold City Eagles",
    "awayTeamId": "Riptide Blue",
    "startsAt": "2026-05-02T09:00:00-05:00",
    "venue": {
      "name": "Field 5",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Green-8U_Riptide_White-09:45",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade",
    "homeTeamId": "Creeks Green",
    "awayTeamId": "8U Riptide White",
    "startsAt": "2026-05-02T09:45:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-12U_Riptide_Blue-Bold_City_Eagles-10:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide Blue",
    "awayTeamId": "Bold City Eagles",
    "startsAt": "2026-05-02T10:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Green-10U_Riptide_Navy-10:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Creeks Green",
    "awayTeamId": "10U Riptide Navy",
    "startsAt": "2026-05-02T10:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Riptide_White-Creeks_Green-10:00",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade",
    "homeTeamId": "Riptide White",
    "awayTeamId": "Creeks Green",
    "startsAt": "2026-05-02T10:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Fleming_Island-10U_Riptide_Gray-10:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Fleming Island",
    "awayTeamId": "10U Riptide Gray",
    "startsAt": "2026-05-02T10:00:00-05:00",
    "venue": {
      "name": "Field 3",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-12U_Riptide_Black-Fleming_Island-10:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide Black",
    "awayTeamId": "Fleming Island",
    "startsAt": "2026-05-02T10:00:00-05:00",
    "venue": {
      "name": "Field 5",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Blue-8U_Riptide_Gray-10:30",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade",
    "homeTeamId": "Creeks Blue",
    "awayTeamId": "8U Riptide Gray",
    "startsAt": "2026-05-02T10:30:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-12U_Riptide_Gray-Jax_Lax-11:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide Gray",
    "awayTeamId": "Jax Lax",
    "startsAt": "2026-05-02T11:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Jax_Lax-10U_Riptide_Black-11:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Jax Lax",
    "awayTeamId": "10U Riptide Black",
    "startsAt": "2026-05-02T11:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Jax_Lax-Riptide_Black-11:00",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade",
    "homeTeamId": "Jax Lax",
    "awayTeamId": "Riptide Black",
    "startsAt": "2026-05-02T11:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Jax_Lax_Titans-10U_Riptide_Blue-11:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Jax Lax Titans",
    "awayTeamId": "10U Riptide Blue",
    "startsAt": "2026-05-02T11:00:00-05:00",
    "venue": {
      "name": "Field 3",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Fleming_Island-Hammerhead-11:00",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade",
    "homeTeamId": "Fleming Island",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-05-02T11:00:00-05:00",
    "venue": {
      "name": "Field 5",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Green-8U_Riptide_Black-11:15",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade",
    "homeTeamId": "Creeks Green",
    "awayTeamId": "8U Riptide Black",
    "startsAt": "2026-05-02T11:15:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-12U_Riptide_Navy-Creeks_Blue-12:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide Navy",
    "awayTeamId": "Creeks Blue",
    "startsAt": "2026-05-02T12:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Blue-10U_Riptide_Navy-12:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Creeks Blue",
    "awayTeamId": "10U Riptide Navy",
    "startsAt": "2026-05-02T12:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Jax_Lax-8U_Riptide_Blue-12:00",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade",
    "homeTeamId": "Jax Lax",
    "awayTeamId": "8U Riptide Blue",
    "startsAt": "2026-05-02T12:00:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-12U_Riptide_Blue-Hammerhead-12:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide Blue",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-05-02T12:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Fleming_Island-Hammerhead-12:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Fleming Island",
    "awayTeamId": "Hammerhead",
    "startsAt": "2026-05-02T12:00:00-05:00",
    "venue": {
      "name": "Field 3",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Blue-Bold_City_Eagles-12:00",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade",
    "homeTeamId": "Creeks Blue",
    "awayTeamId": "Bold City Eagles",
    "startsAt": "2026-05-02T12:00:00-05:00",
    "venue": {
      "name": "Field 5",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Fleming_Island-8U_Riptide_Gray-12:45",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade",
    "homeTeamId": "Fleming Island",
    "awayTeamId": "8U Riptide Gray",
    "startsAt": "2026-05-02T12:45:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-12U_Riptide_Gray-Creeks_Green-13:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide Gray",
    "awayTeamId": "Creeks Green",
    "startsAt": "2026-05-02T13:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Green-10U_Riptide_White-13:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Creeks Green",
    "awayTeamId": "10U Riptide White",
    "startsAt": "2026-05-02T13:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "postponed"
  },
  {
    "id": "lo-jamboree-Hammerhead-Riptide_White-13:00",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Riptide White",
    "startsAt": "2026-05-02T13:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "postponed"
  },
  {
    "id": "lo-jamboree-Jax_Lax_Titans-10U_Riptide_Gray-13:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Jax Lax Titans",
    "awayTeamId": "10U Riptide Gray",
    "startsAt": "2026-05-02T13:00:00-05:00",
    "venue": {
      "name": "Field 3",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "postponed"
  },
  {
    "id": "lo-jamboree-12U_Riptide_White-Fleming_Island-13:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide White",
    "awayTeamId": "Fleming Island",
    "startsAt": "2026-05-02T13:00:00-05:00",
    "venue": {
      "name": "Field 5",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "postponed"
  },
  {
    "id": "lo-jamboree-Jax_Lax-8U_Riptide_Black-13:30",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade",
    "homeTeamId": "Jax Lax",
    "awayTeamId": "8U Riptide Black",
    "startsAt": "2026-05-02T13:30:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "postponed"
  },
  {
    "id": "lo-jamboree-12U_Riptide_Black-Creeks_Blue-14:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide Black",
    "awayTeamId": "Creeks Blue",
    "startsAt": "2026-05-02T14:00:00-05:00",
    "venue": {
      "name": "Field 1",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Jax_Lax-10U_Riptide_White-14:00",
    "seasonSlug": "spring-2026",
    "divisionId": "3/4 Grade",
    "homeTeamId": "Jax Lax",
    "awayTeamId": "10U Riptide White",
    "startsAt": "2026-05-02T14:00:00-05:00",
    "venue": {
      "name": "Field 2",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "postponed"
  },
  {
    "id": "lo-jamboree-Fleming_Island-Riptide_Blue-14:00",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade",
    "homeTeamId": "Fleming Island",
    "awayTeamId": "Riptide Blue",
    "startsAt": "2026-05-02T14:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Creeks_Green-Jax_Lax-14:00",
    "seasonSlug": "spring-2026",
    "divisionId": "7/8 Grade",
    "homeTeamId": "Creeks Green",
    "awayTeamId": "Jax Lax",
    "startsAt": "2026-05-02T14:00:00-05:00",
    "venue": {
      "name": "Field 5",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-Fleming_Island-8U_Riptide_Blue-14:15",
    "seasonSlug": "spring-2026",
    "divisionId": "1/2 Grade",
    "homeTeamId": "Fleming Island",
    "awayTeamId": "8U Riptide Blue",
    "startsAt": "2026-05-02T14:15:00-05:00",
    "venue": {
      "name": "Field 4",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "postponed"
  },
  {
    "id": "lo-jamboree-Hammerhead-Jax_Lax-15:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "Hammerhead",
    "awayTeamId": "Jax Lax",
    "startsAt": "2026-05-02T15:00:00-05:00",
    "venue": {
      "name": "Field 6",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "final"
  },
  {
    "id": "lo-jamboree-12U_Riptide_White-Creeks_Green-15:00",
    "seasonSlug": "spring-2026",
    "divisionId": "5/6 Grade",
    "homeTeamId": "12U Riptide White",
    "awayTeamId": "Creeks Green",
    "startsAt": "2026-05-02T15:00:00-05:00",
    "venue": {
      "name": "Field 5",
      "address": "Julington Creek Plantation Park, St Johns, FL"
    },
    "status": "live"
  }
];
